### ISSUE TITLE
Backend Ansicht

### ISSUE THREAD

**Issue by IngoWinter** [olien/Redaxo-Text-Bild-Modul#2]
Mach dir fürs Backend eine kleine CSS Datei fertig (Twitter Grid innerhalb Modulausgabe), dann kannst du dir das doppelte Markup für Frontend/ Backend sparen.

**Comment by olien** [comment]
Danke. Ziel ist es eh, dass das Modul mit möglichst wenig Abhängigkeiten funktioniert .-)

**Comment by joachimdoerr** [comment]
Warum willst du Abhängigkeiten reduzieren? Es macht doch Sinn die Ressourcen zu nutzen.

**Comment by olien** [comment]
Stimmt. Das Modul soll aber auch für mögliche viele Nutzer nutzbar sein...

**Comment by olien** [comment]
Alles neu :-)
